import {uid} from '../utils/id';
import {levelToOptions} from './levels';
export type EngineStatus='LOADING'|'READY'|'THINKING'|'ERROR';
export interface WdlTriple{w:number;d:number;l:number}
export interface AnalysisResult{requestId:string;bestMove:string|null;ponder:string|null;evaluationCp:number|null;mate:number|null;pv:string[];depth:number;lines?:AnalysisLine[]}
export interface AnalysisLine{moveUci:string;cp:number|null;mate:number|null;pv:string[];depth:number;wdl?:WdlTriple}
const ENGINE_URL='/assets/engine/stockfish.js';
export class StockfishEngine{
 private worker:Worker|null=null;private status:EngineStatus='LOADING';private listeners=new Set<(s:EngineStatus)=>void>();private activeRequestId:string|null=null;private lastError:string|null=null;private multiPV=1;
 async init(timeoutMs=10000){if(this.worker)return;this.worker=new Worker(ENGINE_URL);this.worker.onerror=e=>this.fail(e.message||'Worker error');await this.waitFor(['uciok'],()=>{this.send('uci');this.send('setoption name UCI_ShowWDL value true')},timeoutMs);await this.waitFor(['readyok'],()=>this.send('isready'),timeoutMs);this.setStatus('READY');}
 private waitFor(wanted:string[],start:()=>void,timeout:number){return new Promise<void>((resolve,reject)=>{if(!this.worker)return reject(new Error('worker yok'));const handler=(e:MessageEvent)=>{if(wanted.includes(String(e.data).trim())){this.worker?.removeEventListener('message',handler);clearTimeout(t);resolve();}};const t=setTimeout(()=>{this.worker?.removeEventListener('message',handler);reject(new Error('Motor başlatma zaman aşımı'));},timeout);this.worker.addEventListener('message',handler);start();});}
 private send(c:string){if(!this.worker)throw new Error('Motor hazır değil');this.worker.postMessage(c)}
 private setStatus(s:EngineStatus){this.status=s;this.listeners.forEach(f=>f(s))} private fail(m:string){this.lastError=m;this.setStatus('ERROR')}
 getStatus(){return this.status} getLastError(){return this.lastError} onStatusChange(fn:(s:EngineStatus)=>void){this.listeners.add(fn);return()=>this.listeners.delete(fn)}
 setLevel(level:number){if(!this.worker)return;const o=levelToOptions(level);this.send(`setoption name UCI_LimitStrength value ${o.UCI_LimitStrength}`);if(o.UCI_Elo!==undefined)this.send(`setoption name UCI_Elo value ${o.UCI_Elo}`);this.send(`setoption name Skill Level value ${o.SkillLevel}`)}
 setMultiPV(n:number){this.multiPV=Math.max(1,Math.min(5,Math.round(n)));if(this.worker)this.send(`setoption name MultiPV value ${this.multiPV}`)}
 stop(){if(this.worker&&this.status==='THINKING')this.send('stop');this.activeRequestId=null}
 newGame(){this.stop();this.send('ucinewgame');return this.waitFor(['readyok'],()=>this.send('isready'),5000)}
 analyze(fen:string,opts:{movetimeMs?:number;depth?:number},requestId:string):Promise<AnalysisResult>{return this.analyzeMultiPV(fen,opts,requestId).then(r=>r)}
 analyzeMultiPV(fen:string,opts:{movetimeMs?:number;depth?:number},requestId:string):Promise<AnalysisResult>{if(!this.worker)return Promise.reject(new Error('Motor hazır değil'));this.stop();this.activeRequestId=requestId;this.setStatus('THINKING');this.send(`position fen ${fen}`);this.send(opts.depth?`go depth ${opts.depth}`:`go movetime ${opts.movetimeMs??1000}`);return new Promise((resolve,reject)=>{const lines=new Map<number,AnalysisLine>();let lastDepth=0;const handler=(e:MessageEvent)=>{const line=String(e.data);if(line.startsWith('info')){const d=Number(/depth (\d+)/.exec(line)?.[1]??0);const pv=/ pv (.+)$/.exec(line)?.[1]?.trim().split(/\s+/)??[];const cp=Number(/score cp (-?\d+)/.exec(line)?.[1]??NaN);const mate=Number(/score mate (-?\d+)/.exec(line)?.[1]??NaN);const w=/ wdl (\d+) (\d+) (\d+)/.exec(line);const wdl=w?{w:Number(w[1]),d:Number(w[2]),l:Number(w[3])}:undefined;const multipv=Number(/ multipv (\d+)/.exec(line)?.[1]??1);if(d>=lastDepth)lastDepth=d;const prev=lines.get(multipv);lines.set(multipv,{moveUci:pv[0]??prev?.moveUci??'',cp:Number.isNaN(cp)?prev?.cp??null:cp,mate:Number.isNaN(mate)?prev?.mate??null:mate,pv,depth:d,wdl:wdl??prev?.wdl})}else if(line.startsWith('bestmove')){this.worker?.removeEventListener('message',handler);if(this.activeRequestId!==requestId){reject(new Error('STALE_RESPONSE'));return}this.setStatus('READY');const p=line.trim().split(/\s+/);const arr=[...lines.entries()].sort((a,b)=>a[0]-b[0]).map(x=>x[1]);const top=arr[0];resolve({requestId,bestMove:p[1]&&p[1]!=='(none)'?p[1]:top?.moveUci??null,ponder:p[3]??null,evaluationCp:top?.cp??null,mate:top?.mate??null,pv:top?.pv??[],depth:lastDepth,lines:arr})}};this.worker?.addEventListener('message',handler)})}
 destroy(){this.stop();this.worker?.terminate();this.worker=null;this.listeners.clear();this.setStatus('LOADING')}
}
